# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sputter_gui.ui'
#
# Created: Fri Mar  7 11:27:06 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Specs(object):
    def setupUi(self, Specs):
        Specs.setObjectName(_fromUtf8("Specs"))
        Specs.resize(695, 604)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Specs.sizePolicy().hasHeightForWidth())
        Specs.setSizePolicy(sizePolicy)
        self.gridLayout_3 = QtGui.QGridLayout(Specs)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.start_button = QtGui.QPushButton(Specs)
        self.start_button.setMaximumSize(QtCore.QSize(60, 30))
        self.start_button.setCheckable(False)
        self.start_button.setChecked(False)
        self.start_button.setFlat(False)
        self.start_button.setObjectName(_fromUtf8("start_button"))
        self.gridLayout_2.addWidget(self.start_button, 0, 0, 1, 1)
        self.stop_button = QtGui.QPushButton(Specs)
        self.stop_button.setMaximumSize(QtCore.QSize(60, 30))
        self.stop_button.setObjectName(_fromUtf8("stop_button"))
        self.gridLayout_2.addWidget(self.stop_button, 1, 0, 1, 1)
        self.standby_button = QtGui.QPushButton(Specs)
        self.standby_button.setMaximumSize(QtCore.QSize(80, 16777215))
        self.standby_button.setCheckable(True)
        self.standby_button.setChecked(False)
        self.standby_button.setObjectName(_fromUtf8("standby_button"))
        self.gridLayout_2.addWidget(self.standby_button, 0, 1, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(Specs)
        self.pushButton_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 2, 1, 1)
        self.degas = QtGui.QPushButton(Specs)
        self.degas.setCheckable(True)
        self.degas.setObjectName(_fromUtf8("degas"))
        self.gridLayout_2.addWidget(self.degas, 1, 1, 1, 1)
        self.operate_button = QtGui.QPushButton(Specs)
        self.operate_button.setMaximumSize(QtCore.QSize(80, 16777215))
        self.operate_button.setCheckable(True)
        self.operate_button.setObjectName(_fromUtf8("operate_button"))
        self.gridLayout_2.addWidget(self.operate_button, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_5 = QtGui.QLabel(Specs)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.temp_energy_module = QtGui.QLineEdit(Specs)
        self.temp_energy_module.setMaximumSize(QtCore.QSize(100, 16777215))
        self.temp_energy_module.setObjectName(_fromUtf8("temp_energy_module"))
        self.gridLayout.addWidget(self.temp_energy_module, 0, 1, 1, 1)
        self.filament_current = QtGui.QLineEdit(Specs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filament_current.sizePolicy().hasHeightForWidth())
        self.filament_current.setSizePolicy(sizePolicy)
        self.filament_current.setMinimumSize(QtCore.QSize(50, 30))
        self.filament_current.setMaximumSize(QtCore.QSize(100, 30))
        self.filament_current.setObjectName(_fromUtf8("filament_current"))
        self.gridLayout.addWidget(self.filament_current, 3, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 7, 0, 1, 1)
        self.label_3 = QtGui.QLabel(Specs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.accel_voltage = QtGui.QLineEdit(Specs)
        self.accel_voltage.setMaximumSize(QtCore.QSize(100, 16777215))
        self.accel_voltage.setObjectName(_fromUtf8("accel_voltage"))
        self.gridLayout.addWidget(self.accel_voltage, 5, 1, 1, 1)
        self.label = QtGui.QLabel(Specs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.label_4 = QtGui.QLabel(Specs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(Specs)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.filament_bias = QtGui.QLineEdit(Specs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filament_bias.sizePolicy().hasHeightForWidth())
        self.filament_bias.setSizePolicy(sizePolicy)
        self.filament_bias.setMaximumSize(QtCore.QSize(100, 16777215))
        self.filament_bias.setObjectName(_fromUtf8("filament_bias"))
        self.gridLayout.addWidget(self.filament_bias, 1, 1, 1, 1)
        self.Emissio_current = QtGui.QLabel(Specs)
        self.Emissio_current.setObjectName(_fromUtf8("Emissio_current"))
        self.gridLayout.addWidget(self.Emissio_current, 6, 0, 1, 1)
        self.emission_current = QtGui.QLineEdit(Specs)
        self.emission_current.setMaximumSize(QtCore.QSize(100, 16777215))
        self.emission_current.setObjectName(_fromUtf8("emission_current"))
        self.gridLayout.addWidget(self.emission_current, 6, 1, 1, 1)
        self.sputter_current = QtGui.QLineEdit(Specs)
        self.sputter_current.setMinimumSize(QtCore.QSize(50, 0))
        self.sputter_current.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sputter_current.setObjectName(_fromUtf8("sputter_current"))
        self.gridLayout.addWidget(self.sputter_current, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.quit_button = QtGui.QPushButton(Specs)
        self.quit_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.quit_button.setObjectName(_fromUtf8("quit_button"))
        self.verticalLayout.addWidget(self.quit_button)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.place_holder_qwt = QtGui.QTextBrowser(Specs)
        self.place_holder_qwt.setObjectName(_fromUtf8("place_holder_qwt"))
        self.horizontalLayout.addWidget(self.place_holder_qwt)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(Specs)
        QtCore.QMetaObject.connectSlotsByName(Specs)

    def retranslateUi(self, Specs):
        Specs.setWindowTitle(_translate("Specs", "Form", None))
        self.start_button.setText(_translate("Specs", "Start", None))
        self.stop_button.setText(_translate("Specs", "Stop", None))
        self.standby_button.setText(_translate("Specs", "Standby", None))
        self.pushButton_2.setText(_translate("Specs", "Reset", None))
        self.degas.setText(_translate("Specs", "Degas", None))
        self.operate_button.setText(_translate("Specs", "Operate!", None))
        self.label_5.setText(_translate("Specs", "Acceleration voltage", None))
        self.label_3.setText(_translate("Specs", "Filament current", None))
        self.label.setText(_translate("Specs", "Temperature", None))
        self.label_4.setText(_translate("Specs", "Sputter current", None))
        self.label_2.setText(_translate("Specs", "Filament Voltage", None))
        self.Emissio_current.setText(_translate("Specs", "Emission current", None))
        self.quit_button.setText(_translate("Specs", "Quit", None))

