# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'temperature_controller_gui.ui'
#
# Created: Wed Apr  9 11:46:30 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_temp_control(object):
    def setupUi(self, temp_control):
        temp_control.setObjectName(_fromUtf8("temp_control"))
        temp_control.resize(695, 604)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(temp_control.sizePolicy().hasHeightForWidth())
        temp_control.setSizePolicy(sizePolicy)
        self.gridLayout_3 = QtGui.QGridLayout(temp_control)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.start_button = QtGui.QPushButton(temp_control)
        self.start_button.setMaximumSize(QtCore.QSize(60, 30))
        self.start_button.setCheckable(False)
        self.start_button.setChecked(False)
        self.start_button.setFlat(False)
        self.start_button.setObjectName(_fromUtf8("start_button"))
        self.gridLayout_2.addWidget(self.start_button, 0, 0, 1, 1)
        self.stop_button = QtGui.QPushButton(temp_control)
        self.stop_button.setMaximumSize(QtCore.QSize(60, 30))
        self.stop_button.setObjectName(_fromUtf8("stop_button"))
        self.gridLayout_2.addWidget(self.stop_button, 1, 0, 1, 1)
        self.standby_button = QtGui.QPushButton(temp_control)
        self.standby_button.setMaximumSize(QtCore.QSize(80, 16777215))
        self.standby_button.setCheckable(True)
        self.standby_button.setChecked(False)
        self.standby_button.setObjectName(_fromUtf8("standby_button"))
        self.gridLayout_2.addWidget(self.standby_button, 0, 1, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(temp_control)
        self.pushButton_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 2, 1, 1)
        self.degas = QtGui.QPushButton(temp_control)
        self.degas.setCheckable(True)
        self.degas.setObjectName(_fromUtf8("degas"))
        self.gridLayout_2.addWidget(self.degas, 1, 1, 1, 1)
        self.operate_button = QtGui.QPushButton(temp_control)
        self.operate_button.setMaximumSize(QtCore.QSize(80, 16777215))
        self.operate_button.setCheckable(True)
        self.operate_button.setObjectName(_fromUtf8("operate_button"))
        self.gridLayout_2.addWidget(self.operate_button, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.power = QtGui.QLineEdit(temp_control)
        self.power.setMaximumSize(QtCore.QSize(100, 16777215))
        self.power.setObjectName(_fromUtf8("power"))
        self.gridLayout.addWidget(self.power, 5, 1, 1, 1)
        self.current = QtGui.QLineEdit(temp_control)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.current.sizePolicy().hasHeightForWidth())
        self.current.setSizePolicy(sizePolicy)
        self.current.setMinimumSize(QtCore.QSize(50, 30))
        self.current.setMaximumSize(QtCore.QSize(100, 30))
        self.current.setObjectName(_fromUtf8("current"))
        self.gridLayout.addWidget(self.current, 3, 1, 1, 1)
        self.label_3 = QtGui.QLabel(temp_control)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.Emissio_current = QtGui.QLabel(temp_control)
        self.Emissio_current.setObjectName(_fromUtf8("Emissio_current"))
        self.gridLayout.addWidget(self.Emissio_current, 6, 0, 1, 1)
        self.label_2 = QtGui.QLabel(temp_control)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.setpoint = QtGui.QLineEdit(temp_control)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setpoint.sizePolicy().hasHeightForWidth())
        self.setpoint.setSizePolicy(sizePolicy)
        self.setpoint.setMaximumSize(QtCore.QSize(100, 16777215))
        self.setpoint.setObjectName(_fromUtf8("setpoint"))
        self.gridLayout.addWidget(self.setpoint, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(temp_control)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.resistance = QtGui.QLineEdit(temp_control)
        self.resistance.setMaximumSize(QtCore.QSize(100, 16777215))
        self.resistance.setObjectName(_fromUtf8("resistance"))
        self.gridLayout.addWidget(self.resistance, 6, 1, 1, 1)
        self.voltage = QtGui.QLineEdit(temp_control)
        self.voltage.setMinimumSize(QtCore.QSize(50, 0))
        self.voltage.setMaximumSize(QtCore.QSize(100, 16777215))
        self.voltage.setObjectName(_fromUtf8("voltage"))
        self.gridLayout.addWidget(self.voltage, 2, 1, 1, 1)
        self.temperature = QtGui.QLineEdit(temp_control)
        self.temperature.setMaximumSize(QtCore.QSize(100, 16777215))
        self.temperature.setObjectName(_fromUtf8("temperature"))
        self.gridLayout.addWidget(self.temperature, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(temp_control)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label = QtGui.QLabel(temp_control)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 8, 0, 1, 1)
        self.label_6 = QtGui.QLabel(temp_control)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 7, 0, 1, 1)
        self.new_setpoint = QtGui.QLineEdit(temp_control)
        self.new_setpoint.setMaximumSize(QtCore.QSize(100, 30))
        self.new_setpoint.setObjectName(_fromUtf8("new_setpoint"))
        self.gridLayout.addWidget(self.new_setpoint, 7, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.quit_button = QtGui.QPushButton(temp_control)
        self.quit_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.quit_button.setObjectName(_fromUtf8("quit_button"))
        self.verticalLayout.addWidget(self.quit_button)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.place_holder_qwt = QtGui.QTextBrowser(temp_control)
        self.place_holder_qwt.setObjectName(_fromUtf8("place_holder_qwt"))
        self.horizontalLayout.addWidget(self.place_holder_qwt)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(temp_control)
        QtCore.QMetaObject.connectSlotsByName(temp_control)

    def retranslateUi(self, temp_control):
        temp_control.setWindowTitle(_translate("temp_control", "Form", None))
        self.start_button.setText(_translate("temp_control", "Start", None))
        self.stop_button.setText(_translate("temp_control", "Stop", None))
        self.standby_button.setText(_translate("temp_control", "Standby", None))
        self.pushButton_2.setText(_translate("temp_control", "Reset", None))
        self.degas.setText(_translate("temp_control", "Degas", None))
        self.operate_button.setText(_translate("temp_control", "Operate!", None))
        self.label_3.setText(_translate("temp_control", "Current", None))
        self.Emissio_current.setText(_translate("temp_control", "Resistance", None))
        self.label_2.setText(_translate("temp_control", "Actual setpoint", None))
        self.label_4.setText(_translate("temp_control", "Voltage", None))
        self.label_5.setText(_translate("temp_control", "Power", None))
        self.label.setText(_translate("temp_control", "Temperature", None))
        self.label_6.setText(_translate("temp_control", "New setpoint", None))
        self.quit_button.setText(_translate("temp_control", "Quit", None))

