
from __future__ import unicode_literals, print_function
import os
import sys

# Paths
THIS_DIR = os.path.dirname(os.path.realpath(__file__))
AUTOGEN_ONLY_NAME = 'drivers-autogen-only'
DRIVERDIR = os.path.join(THIS_DIR, '..', '..', 'PyExpLabSys', 'drivers')
DRIVER_FILES = os.listdir(os.path.join(THIS_DIR, 'drivers'))
DRIVER_FILES_AUTOGEN_ONLY = os.listdir(os.path.join(THIS_DIR, AUTOGEN_ONLY_NAME))

RST_TEMPLATE = \
'''..
   This file has been autogenerated

   If you wish to add more content e.g. usage examples please also move the file from the
   {autogen_only_name} folder to the drivers folder.

.. _drivers-doc-{modulename}:

****{stars}*******
The {modulename} module
****{stars}*******

Autogenerated API documentation for {modulename}
===================================={equals}

.. automodule:: PyExpLabSys.drivers.{modulename}
   :members:
   :member-order: bysource
   :show-inheritance:

'''

def main():
    """Main function"""
    autogen_stubs_not_encountered = set(DRIVER_FILES_AUTOGEN_ONLY)
    
    for file_ in os.listdir(DRIVERDIR):
        filename, extension = os.path.splitext(file_)

        # Only .py files that does not starts with __
        if filename.startswith('__') or extension != '.py':
            continue

        # Check if we already know about the module
        rst_filename = filename + '.rst'
        if rst_filename in autogen_stubs_not_encountered:
            autogen_stubs_not_encountered.remove(rst_filename)
        if rst_filename in DRIVER_FILES or rst_filename in DRIVER_FILES_AUTOGEN_ONLY:
            print('Already know about:', filename)
            continue

        mod_name_len = len(filename)
        content = RST_TEMPLATE.format(
            modulename=filename,
            stars='*' * len(filename),
            equals='=' * len(filename),
            autogen_only_name=AUTOGEN_ONLY_NAME,
        )


        full_rst_path = os.path.join(THIS_DIR, AUTOGEN_ONLY_NAME, rst_filename)
        with open(full_rst_path, 'wb') as file_:
            file_.write(content.encode('ascii'))
        print('Wrote out:', full_rst_path)

    if not autogen_stubs_not_encountered:
        return

    print()
    if len(sys.argv) > 1 and sys.argv[1] == 'DELETE':
        for stub in autogen_stubs_not_encountered:
            path = os.path.join(THIS_DIR, AUTOGEN_ONLY_NAME, stub)
            os.remove(path)
    else:
        print('NOTE: There are autogenerated stub files that point to drivers '
              'that no longer exits. It is the following files:')
        for stub in autogen_stubs_not_encountered:
            print(os.path.join(THIS_DIR, AUTOGEN_ONLY_NAME, stub))
        print('To delete them, call this script again with the word DELETE as the only argument')

main()
